name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    name: Verify & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.4.1

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter api exec prisma generate

      - name: Check TypeScript types
        run: pnpm check-types

      - name: Lint Code
        run: pnpm lint

      - name: Build Projects
        run: pnpm build
